version: '3.7'
services:
  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: env('DB_USER')
      POSTGRES_PASSWORD: env('DB_PASSWORD')
      POSTGRES_DB: env('DB_NAME')
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - ./database:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  database: